name: blog

services:
  app:
    build: .
    image: blog-app-image
    container_name: blog-app-container
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis 


  postgres:
    image: postgres
    container_name: blog-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: "redis:alpine"
    container_name: blog-redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      -  redis_data:/data


  celery:
    image: blog-app-image
    container_name: blog-celery-container
    command: celery -A Blogs worker -E -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - app


  flower:
    image: blog-app-image
    container_name: blog-flower-container
    command: celery -A Blogs flower
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
    
      
  esearch:
    image: elasticsearch:8.13.0
    container_name: blog-esearch-container
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esearch_data:/usr/share/elasticsearch/data


volumes:
  postgres_data: 
  redis_data:
  esearch_data: